#site settings
title: Jonathan Firth – Psychology of Education
description: I am an author, university teacher and researcher. I have authored several books relating to the psychology of education, as well as school psychology textbooks.
url: "jonathanfirth.co.uk"
baseurl: ""

#build settings
theme: minima

#other config
header_pages:
- index.md
- about.md
- books.md
- contact.md

social_links:
- title: Bluesky
  icon: bluesky
  url: https://bsky.app/profile/jwfirth.bsky.social