#site settings
title: Jonathan Firth – Psychology of Education
description: This is the summary that shows up in google search results

twitter_username: JW_Firth

#build settings
theme: minima