#site settings
title: Jonathan Firth – Psychology of Education
description: This is the summary that shows up in google search results
url: "https://neezes.github.io"
baseurl: "/skills-github-pages"

email:
twitter_username: JW_Firth

#build settings
theme: minima

#other config
header_pages:
- index.md
- about.md
- books.md